name: Test

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
#  macos:
#    name: Running tests on ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os:
#          - macos-10.15
#    runs-on: ${{ matrix.os }}
#    steps:
#
#      - name: Git clone repository
#        uses: actions/checkout@v2
#      #- name: Setup tmate session, see https://github.com/marketplace/actions/debugging-with-tmate
#      #  uses: mxschmitt/action-tmate@v3
#      - name: Prepare machine
#        run:  |
#          brew install automake
#      - name: Run the tests
#        run:  |
#          tools/setup \
#          && ./configure --enable-libtap \
#          && make \
#          && make test

  linux:
    runs-on: ubuntu-latest
    name: Running tests on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          #- 'debian:10'
          - 'debian:testing'
          #- 'ubuntu:20.10'
          #- 'centos:7'
          #- 'centos:8'
        include:
          #- distro: 'debian:10'
          #  prepare: .github/prepare_debian.sh
          - distro: 'debian:testing'
            prepare: .github/prepare_debian.sh
          #- distro: 'ubuntu:20.10'
          #  prepare: .github/prepare_debian.sh
          #- distro: 'centos:7'
          #  prepare: .github/prepare_centos.sh
          #- distro: 'centos:8'
          #  prepare: .github/prepare_centos.sh
    steps:
      - name: Git clone repository
        uses: actions/checkout@v2
      #- name: Setup tmate session, see https://github.com/marketplace/actions/debugging-with-tmate
      #  uses: mxschmitt/action-tmate@v3
      - name: Run the tests on ${{ matrix.distro }}
        run: |
          docker volume create --driver local --opt type=tmpfs --opt device=tmpfs --opt o=size=100m,uid=1000 tmp-vol
          docker run \
              -e NPTEST_ACCEPTDEFAULT=1 \
              -e NPTEST_CACHE="/src/.github/NPTest.cache" \
              -w /src -v ${PWD}:/src \
              --tmpfs /media/ramdisk1 \
              --mount source=tmp-vol,destination=/src,target=/media/ramdisk2 \
              ${{ matrix.distro }} \
              /bin/sh -c '${{ matrix.prepare }} && \
                tools/setup && \
                ./configure --enable-libtap && \
                make && \
                make test'
          docker volume rm tmp-vol
